api_version = "2024-07"

[[extensions]]
type = "ui_extension"
name = "purchase-orders-pos"
handle = "purchase-orders-pos"
description = "Purchase Orders"

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
