services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  gotenberg:
    image: gotenberg/gotenberg:8
    restart: always
    ports:
      - "3001:3000"
