schema:
  - "https://${SHOPIFY_SHOP}/admin/api/2024-01/graphql.json":
      headers:
        "X-Shopify-Access-Token": "${SHOPIFY_ACCESS_TOKEN}"
documents: "**/queries/*.graphql"
extensions:
  genql:
    schemaOutput: "./services/gql/queries/generated/schema.ts"
    schemaInput: "./services/gql/queries/generated/schema.js"
    documentsOutput: "./services/gql/queries/generated/queries.ts"
    scalarTypes:
      FormattedString: "string"
      URL: "string"
      Money: "`${ number}`"
      Decimal: "`${ number}`"
      DateTime: "string"
    requiredTypes:
      - "MoneyV2"
      - "Attribute"
      - "Metaobject"
    documentHeader:
      - "/* eslint-disable */"
      - "import type { Graphql } from '@teifi-digital/shopify-app-express/services/graphql.js';"
    queryTransformation: "(graphql: Graphql, variables: Variables & Record<string, any>) => graphql.query<Result>(query, Object.fromEntries(Object.entries(variables).filter(([k, v]) => v !== undefined && v !== null)))"
    brandedScalars:
      - "ID"
      - "Money"
      - "Int"
      - "DateTime"
      - "Decimal"
