schema:
  - "https://${SHOPIFY_SHOP}/admin/api/2023-07/graphql.json":
      headers:
        "X-Shopify-Access-Token": "${SHOPIFY_ACCESS_TOKEN}"
documents: "**/queries/*.graphql"
extensions:
  genql:
    schemaOutput: "./services/gql/queries/generated/schema.ts"
    schemaInput: "./services/gql/queries/generated/schema.js"
    documentsOutput: "./services/gql/queries/generated/queries.ts"
    scalarTypes:
      FormattedString: "string"
      URL: "string"
      Money: "`${ number}.${ number}`"
    documentHeader:
      - "import type { Graphql } from '@teifi-digital/shopify-app-express/services/graphql.js';"
    queryTransformation: "(graphql: Graphql, variables: Variables & Record<string, any>) => graphql.query<Result>(query, variables)"
    brandedScalars:
      - "ID"
