api_version = "2024-07"

[[extensions]]
type = "ui_extension"
name = "new-work-order-pos"
handle = "new-work-order-pos"
description = "New Work Order"

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"
