api_version = "2024-10"

[[extensions]]
name = "t:name"
handle = "reorder-point-admin-product"
type = "ui_extension"


# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/BlockExtension.tsx"
# The target used here must match the target used in the module file (./src/BlockExtension.tsx)
target = "admin.product-details.block.render"

