api_version = "2024-07"

[[extensions]]
type = "ui_extension"
name = "work-orders-pos"
handle = "work-orders-pos"
description = "Work Orders"

[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"
