name: Push

on:
  push:
    branches:
      - staging
      - production

jobs:
  app:
    name: App
    uses: teifi-digital/workflows/.github/workflows/teifi-shopify-app.yml@main
    secrets: inherit
    with:
      extensions_install_command: npm run all:install && npm run all:build
      build_arg_env_vars: VITE_INTERCOM_APP_ID
      app_proxy: true
      pos_embedded: true
      deploy-autogen-values: ${{ github.ref != 'refs/heads/production' }}
