name: Push

on:
  push:
    branches:
      - staging
      - production

jobs:
  app:
    name: App
    uses: teifi-digital/workflows/.github/workflows/teifi-shopify-app.yml@feature/k8s-deployment
    secrets: inherit
    with:
      extensions_install_command: npm run all:install && npm run all:build
      custom_build_args: |
        VITE_INTERCOM_APP_ID=${{ vars.VITE_INTERCOM_APP_ID }}
      deploy-autogen-values: ${{ github.ref != 'refs/heads/production' }}
