name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  teifi-shopify-app:
    uses: teifi-digital/workflows/.github/workflows/teifi-shopify-app.yml@master
    with:
      name: "WorkMate"
      shopify_api_key: ${{ vars.SHOPIFY_API_KEY }}
      shopify_shop: ${{ vars.SHOPIFY_SHOP }}
      sentry_org: ${{ vars.SENTRY_ORG }}
      sentry_project: ${{ vars.SENTRY_PROJECT }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      deploy_extensions: true
      extensions_install_command: npm run all:install && npm run all:build
    secrets: inherit
